version: "3"
services:
  java:
    build:
      context: .
      dockerfile: docker/dockerfile-java
    volumes:
      - ./:/code
    working_dir: /code
    command: tail -f /dev/null
    tty: true
    ports:
      - 8999:8080
  postgres:
    image: "postgres:9.6"
    environment:
      POSTGRES_DB: beacon
      POSTGRES_USER: beacon
      POSTGRES_PASSWORD: password
