branch-defaults:
  default:
    environment: prod-tomcat-beacon
environment-defaults:
  prod-tomcat-beacon:
    branch: null
    repository: null
global:
  application_name: prod-tomcat
  default_ec2_keyname: tomcat-dev-key
  default_platform: arn:aws:elasticbeanstalk:eu-west-1::platform/Tomcat 8.5 with Java
    8 running on 64bit Amazon Linux/3.1.0
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
